[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1

[Metadata]
Name=SkinTray
Author=nstechbytes
Information=This skin tests the Tray Icon Plugin with various mouse actions.
License=MIT License
Version=1.3

[Variables]
Action=Perform Action in Tray Icon

[Calc]
Measure=Calc
Formula=Calc = 0 ? 1 : 0

[MeasureTrayIcon]
Measure=Plugin
Plugin=SkinTray
Disabled=0
Icon="#@#Icon[Calc].ico"
ToolTipText=Tray Icon [Calc]
;Dark and White Context Menu
DarkContext=0
; Mouse click actions
LeftMouseUpAction=[!Log "Left Mouse Action"][!SetVariable Action  "Left Mouse Action"][!UpdateMeter *][!Redraw]
RightMouseUpAction=[!Log "Right Mouse Action"][!SetVariable Action  "Right Mouse Action"][!UpdateMeter *][!Redraw]
MiddleMouseUpAction=[!Log "MiddleMouseUpAction"][!SetVariable Action  "MiddleMouseUpAction"][!UpdateMeter *][!Redraw]
DoubleClickAction=[!Log "Double Click Action"][!SetVariable Action  "Double Click Action"][!UpdateMeter *][!Redraw]
; Mouse wheel actions
MouseWheelUpAction=[!Log "Mouse ScrollUp"][!SetVariable Action  "Mouse ScrollUp"][!UpdateMeter *][!Redraw]
MouseWheelDownAction=[!Log "Mouse Scrolldown"][!SetVariable Action  "Mouse Scrolldown"][!UpdateMeter *][!Redraw]
; Context menu configuration (optional)
ContextMenuItemCount=2
ContextMenuItem1=Action One
ContextMenuAction1=[!Log "Context Menu Action One"][!SetVariable Action  "Context Menu Action One"][!UpdateMeter *][!Redraw]
ContextMenuItem2=Action Two
ContextMenuAction2=[!Log "Context Menu Action Two"][!SetVariable Action  "Context Menu Action Two"][!UpdateMeter *][!Redraw]
DynamicVariables=1
ShowOnTaskbar=1

[Meter_Shape]
Meter=Shape
Shape=Rectangle 0,0,200,100,8 | StrokeWidth 0 | FillColor 10,10,10,100

[MeterString]
Meter=String
Text=#Action#
X=100
Y=50
H=100
W=200
StringAlign=CenterCenter
FontColor=255,255,255
AntiAlias=1
DynamicVariables=1
